AWSTemplateFormatVersion: 2010-09-09
Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The environment name your service, job, or workflow is being deployed to.
  Name:
    Type: String
    Description: The name of the service, job, or workflow being deployed.
Mappings: 
  AccountMap: 
    '264126593162': 
      VpcId: vpc-09c4429329f753e0c
      EnvironmentName: Test
      DatabaseSubnets: subnet-0ad9e870f74801f17, subnet-0ffa2a27c68f0782d, subnet-0b0e529004420cce1
      NotificationEmail: jonesaws@amazon.com
Resources:
  DBNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: !FindInMap [AccountMap, !Ref AWS::AccountId, NotificationEmail]
        Protocol: email
  AppSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Limited SG for App
      VpcId: !FindInMap [AccountMap, !Ref AWS::AccountId, VpcId]
  MyRDSInstanceRotationSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ['-',[!Ref AWS::StackName,'DbCredentials']]
      Description: Generated Admin RDS Credentials
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
    
Outputs:
  ApplicationSecurityGroup:
    Description: App DB Access Security Group
    Value: !Ref AppSecurityGroup
  DatabaseCredentials:
    Description: The Database credentials from secrets manager
    Value: !Ref MyRDSInstanceRotationSecret